# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/locations/*"
  to = "/index.html"
  status = 200

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.staging.environment] # 'staging' is a branch name
    SPREADSHEET_ID = "1FQJHr9FR8Qgprzh8ggxQs4_InP4bZIJhEwDgAlbcOAQ"
